language: node_js
node_js:
- 8
addons:
  postgresql: "9.5"
  apt:
    packages:
    - postgresql-9.5-postgis-2.3
services:
- postgresql
install: yarn;
before_script: yarn init-local-db;
script: yarn test;
deploy:
  - provider: script
    script: bash ./deployment/deploy.sh prod
    on:
      # branch: master
      condition: |
        branch = dev-travis-hack OR \
        false
  - provider: script
    script: bash ./deployment/deploy.sh prod-legacy-sync
    on:
      # branch: master
      condition: |
        branch = dev-travis-hack OR \
        false
  # - provider: script
  #   script: bash ./deployment/deploy.sh
  #   on:
  #     condition: |
  #       false OR \
  #       branch = dev-travis-hack
