language: node_js
node_js:
- 8
addons:
  postgresql: "9.5"
  apt:
    packages:
    - postgresql-9.5-postgis-2.3
services:
- postgresql
install: yarn;
before_script: yarn init-local-db;
script: yarn test;
deploy:
  - provider: script
    script: bash ./deployment/test-env-1.sh; bash ./deployment/deploy.sh;
    on:
      branch: dev-travis-hack
  - provider: script
    script: bash ./deployment/test-env-2.sh; bash ./deployment/deploy.sh;
    on:
      branch: dev-travis-hack
