language: node_js
node_js:
- 10
addons:
  postgresql: '10'
  apt:
    packages:
    - postgresql-10-postgis-2.4
    - postgresql-10-postgis-2.4-scripts
    - postgresql-client-10
services:
- postgresql
env:
  global:
  - PGPORT=5433
install:
  - yarn
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
before_script:
  - psql -p 5433 -c "ALTER USER travis WITH PASSWORD 'travis';"
  - yarn init-local-db;
script: yarn test;
deploy:
  - provider: script
    script: bash ./deployment/timeoutWrapper.sh prod
    on:
      branch: master
  - provider: script
    script: bash ./deployment/timeoutWrapper.sh prod-legacy-sync
    on:
      branch: master
  - provider: script
    script: bash ./deployment/timeoutWrapper.sh
    on:
      all_branches: true
      condition: "$(node ./deployment/shouldDeploy.js) = true"
