language: node_js
node_js:
- 8
addons:
  postgresql: "9.5"
  apt:
    packages:
    - postgresql-9.5-postgis-2.3
services:
- postgresql
install: yarn; yarn global add serverless@1.25.0;
before_script: yarn init-local-db;
script: yarn test
deploy:
  provider: script

    # Deal with this
    # env PGENDPOINT=cptfgvdskz2sa2.cg5ybcpnkj4u.us-east-1.rds.amazonaws.com \

    # env npm_config_PGCON=postgresql://example:serverless@cptfgvdskz2sa2.cg5ybcpnkj4u.us-east-1.rds.amazonaws.com:5432/floods \
    # env POSTGRAPHQL_ENDPOINT=https://fzd0rh62c5.execute-api.us-east-1.amazonaws.com/dev/graphql \
    # env FRONTEND_URL=ctxfloods-frontend-master.s3-website-us-east-1.amazonaws.com \
  script: yarn deploy
  on:
    branch: dev-travis
env:
- AWS_SERVICE_NAME=ctx-floods-backend-dev-travis
- AWS_ACCESS_KEY_ID=$ACCESS_KEY_ID_DEV_TRAVIS
- AWS_SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY_DEV_TRAVIS
- GMAIL_ADDRESS=$GMAIL_ADDRESS_DEV_TRAVIS
- GMAIL_PASSWORD=$GMAIL_PASSWORD_DEV_TRAVIS
- JWT_SECRET=$JWT_SECRET_DEV_TRAVIS
- PGUSERNAME=example
- PGPASSWORD=serverless
    # condition: $TRAVIS_PULL_REQUEST_BRANCH = dev-travis
  # - provider: script
  #   script: |
  #   env SERVICE_NAME=ctx-floods-backend-dev-travis-again \
  #   env AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_FLOODS_BACKEND_DEV_TRAVIS \
  #   env AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_FLOODS_BACKEND_DEV_TRAVIS \
  #   env GMAIL_PASSWORD=$GMAIL_PASSWORD_DEV_TRAVIS \
  #   env JWT_SECRET=$JWT_SECRET_DEV_TRAVIS \
  #   sls deploy -v;
  #   on:
  #     branch: dev-travis
  #     condition: "$AWS_ACCESS_KEY_ID"
  # - provider: script
  #   script: deploy-from-local
  #   on:
  #     branch: /^dev-.*$/
  #     condition: "$AWS_ACCESS_KEY_ID"
