language: node_js
node_js:
- 8
addons:
  postgresql: 9.5
  apt:
    packages:
    - postgresql-9.5-postgis-2.3
services:
- postgresql
install: yarn;
before_script: yarn init-local-db; yarn local-drop-rebuild;
script: yarn start-express-server & yarn test;
deploy:
  provider: script
  script: yarn add global serverless@1.25.0; yarn; yarn rebuild-and-deploy-with-tons-of-crossings;
  on:
    all_branches: true
    condition: "$AWS_ACCESS_KEY_ID"
env:
  global:
  - secure: OQ9WcN7V/uFOe7vbPkQNpSVpjxaz84JKY8lXa1y4YVJ9cjajxC7v9vJ0xLj7rctzAl2O4t2FFJwn+myJkO638WzSsjNuK2KApa8nbP+jAGaDRF6r5MWiH8KwyVP/iqASqLWGlF8hmEZO24ky7mP1OVih1++LqBOfcIq9bPj+DHVFAsAyDrlDzpAClW7/TgwZmFIwTQurJ+JIdQHJuOspIJHUW/KNg4vkaMb7Fd3KPhmicV6XkbrmL3ALSi1BSpxh/B6m8MXg+kvw5wMD3G5+dj2y1LQD3iujcuGkBcOca6H98dG0PK+T6jeg8/Pf6z+EhpyO8dnknV6qw8PboNYaiJYbYnaZ6leSXQKmXJfpMf96d4CEMhTuIKZ5SzbmU/SLApPtghyvZFY5DP5QAaqigM8zRwQksJCAIvIvnq5Vs+6U+gCbRAsX40idz7hbFbZTojz9dYqNGwNhEMN2usHNn750M7aQW/iSg6uIoJozal/lr5Y3y/RJNY0eYFTx0CAR9RcyPqr+iEMrKGCxbaKcoQPYx4Gcr6BTV2GS0yrhT6JExN1Dvs75lLPWwcbhAZ0trBxQtlCAUVsQXqr+Bhx2zG1LgUrxVZ7jvGwqGf7JMTHeKL7OKha3pCdYe9x9/fTULvSvQxFpN6A9CSqkSmCzQ6PG9pX9xq0ZRmEThl07C20=
  - secure: VPlxsbDOQlRvtDNuXkl8UVsTcZyVaq5GhcZPKXQOivz9kJ9wy++EEhn9z6g/o2EN3TvBxZUt7ORIrH7kEvPbYVFEDvQ7s6Cpn0HU/p0QA0aDnVj7J1SgQFsGiyHF46nGJ8XAXBkAkiOWNXgUyeuCPxAacVUBsspWRM8OWrOTFRAXUgXyVcLg/fjp+uXGsaj5Szn4hSL7AxPxcBE3xovwkRGGmWAQ6sQEv1lVjDBfRXW5TScsnb76ytizPzdQ9+jb/njdz3uRfwXFaFULwoPqOTQGPi+DyPU3XRk7f+pkMy8N9V6sJByZA/Vi2RZ7zjEIndggIJW9mWy9SPZxcDfMJE8SHsnh+dVF+InrlLaESyaLrF/FE0LacXu5uY5saR9G24IldcRuEN06HPSZFOBwXlKxAW4R2dnw+ZqXxy0e5OWSV0VH4YxxGrFEI9rR45QrL1V3AZhyivcaFxoPWN4wGt5Kghx53HxitMk4kuUzmh3Rqph1QZ2gK3VuPFXDk0Gt9MNugR4YEe8vQlvmwuu6xsuBLG9eLyIa6ZmkE164RS9ag+ZFn2dtzAfW2XaZEgYoGWkZIhiJq9433MdegYvrdVLz7V5fxa+Ya4LMbzjc/2N/8m6raj9b0PsTVh9ZA66gF8l0NGSHckMq1e+j+ED/tqZH9CVck89vdmMK0N8CpgY=
  - secure: LqaAlRfIGhaY0c3+reeQafJbru3c1/kBtKrqtjaMJjFbVc1j9HrJbgHPaEaAPeelLi4jHNhfyksQkOlZKrqixGwVoyk/qpmESk8He5V2azpOCxzoGiLvkWTwzVpjPYxqA34VeLhqM1+BL18luYMuNKfqLAiqcsxRCOn6E4I5FodsVFdfeCjcNwlcKAmC87dkBcVx1aS0LXeltMJyIZ5MFdgkpp8lRPGoFSE0kDc1Po1Z+W9fX4cXgi+5nhZsFV+tOmFgxRVRA4dH23obrO5NfJ33CT0QdjA88z05QpdpxQ3LsyU05k88/tehVMPKs3VafEDhNK053QC9JR42SOeOFT2im/2YvD3kJYz4wGnsRZemjJHi6Np5qKDPPlgOgIlxogp9pdoFn4SeL34LrNH9QuO29txNQv4kWrwdIkVSX6MTdj5gZsCJzdOqyHSUU5fXFXOpBDW2qYeBS4v2S4uU2Nx5C/6mZQUhG6/mOiK4WJVNert31iB2nMHfTU/BplGWXU+S4G1FJy1y/v47q1mp6tCjipThtP6yGit/zD44MCRqvCbujqhYcuEIg0bDWCJToXGKZbVf+kfDag0bqfBDuebMGlAYQMDJYLuIaJaDVzdEgnxLoWI/VrAGW1nMzjqJ+flIaY+aSfQ5ra6mc5E2PredLETOlvpXTlG69ehRIZs=
  - secure: JddPAjhfYHOpKr4jTnh6lS7eUTtN2HnDj7Lexzzh9OFgpG1BOPNqP1ERhz+zOCKddQbG0sAjEl4wdJ8LeMCIvLa9jq9hfmd2ddiuIYLqEDPh5cc3rfeXvHLVvt30ZCSlG19WsMgJoG2gj6IfmO9cgdgWBt6QpKf5rES/P5KM2Swzxq65WRmDIg0747qF6b+81/pkTgdb2Gfs68v9kW3/qy1Zw0QEe3Pt/T0xcJuBq5dhfcGyj411Dc99pVuzWdudQviqwxuBUic6WVgvPyq+a7AsbOceA8JRK+cLQ6DgtEuwcduqTKYuMmzN8SrnlMDCFC59u1/Icv063O+K/2EmEb1BPhv4VDXn5/bIcNHy9TqbsEbC2owIm2mT1J2eihqR1g1tapCconWd8k5ZAxAZnbO651RGm9Q1oQGx/f40e3KS5cQxMwadPtJnoOlMtug+7z87PkJDfvFT+614ryc4aSAbZ+kiO7leJaqcmT1Qu5ofCwgsmehIQP7OP4iVUnImDN58Kx9/l+xTB5fAE2yY4/fl+rO6h5BT0CAVibz9gSKB4GydLstYjwnGMTCaK9TU1I+/uWLhei1C8euW9iXJewoH9uegk1IXbDpcUgXiCmpQs6XK9Y1ypbLzyM/jmUvtmEH5yOnRxr9MxFxP+nnY0+sW50eCkKYIKENVI7M5Gdw=
  - npm_config_PGCON=postgresql://example:serverless@cptfgvdskz2sa2.cg5ybcpnkj4u.us-east-1.rds.amazonaws.com:5432/floods
  - npm_config_PGRUNCON=postgresql://floods_postgraphql:xyz@cptfgvdskz2sa2.cg5ybcpnkj4u.us-east-1.rds.amazonaws.com:5432/floods
  - POSTGRAPHQL_ENDPOINT=https://fzd0rh62c5.execute-api.us-east-1.amazonaws.com/dev/graphql
  - CURRENT_FLOODS_BRANCH_NAME=master
  - FRONTEND_URL=ctxfloods-frontend-master.s3-website-us-east-1.amazonaws.com
  - GMAIL_ADDRESS=ctxfloodstestmailer@gmail.com
