language: node_js
node_js:
- 8
addons:
  postgresql: 9.5
  apt:
    packages:
    - postgresql-9.5-postgis-2.3
services:
- postgresql
install: yarn;
before_script: yarn init-local-db;
script: yarn test;
deploy:
  provider: script
  script: yarn add global serverless@1.25.0; yarn; yarn deploy;
  on:
    all_branches: true
    condition: "$AWS_ACCESS_KEY_ID"
env:
  global:
  - secure: RCNqDxQP53XhLaU0pr0F0VzbKpDGDFg5ShoeKqvFGwEtuBPCHr/a0LHhy4GMiw8scE2bcKyXMIIDdnvbnOiLlUTy8b4YLioYhwV3F+e+Ey9Dr4pU7bcu9NoDzJUjS1+FGkCTB5hSMQ6PW4vBOUYd27d0ilOMlPnrej4hzMFjHdDuEkInlTH8qoBa9rxWU0nrHvqDQGpm3k+OXSn1swa9VmJkgspXYM8JC2ApCmNaCyMBsugKdmubFYshA/Xdndl6sbKOqHc96bohY47a+zFbGUg2B0KRz3H1C5A7NjOlS+AGnXZX9As38Lpi6s3sVynTAQfE6w8zKMNZB5RGtpDv55rTmXjnM5588ugkWTA3Ev/N6Wu8Kero5BJxGTzyyN56MiNvZDlqt/6qlEn6c/AlE8Kng+HgfrcomY08CGGbX+wlUqF2eCF/4JYInLsWabpwEETQzm/NmE6wm6QBJb+RhjllKRWnwSlUrkNn6FGdjw6hRgELfQhh5fQlzWlLRm45HDPq/hT1TF06/Qnsyq8rEpAbbGMRH6M+CLO3/4zSyVMt8yAV6GwNEkVYjr5PgC/ORXJuAQcuIG+2NfA3XV5MortJQjDwGXZiLWiTQn4TZR7BCmwlOTtaYdMJ9iF3nJEBEIdQGcpH9AQ0dP9wsU75cTV8lFYrOeWCbXOljdvNar8=
  - secure: hZkx/zeWkmI+ilNMz4O3nk97e6eTUwTZjCNJpngFJQdqhalBYettMbSDajl7iBYs8f4Rb75j8aJl2v2mjn1XsjhGPzsIrkAdzAWWfUYlETuKL89UtJ1lNL+2jDVGBxyS6jUQkp1VMqHKz5vEPI5PlLt9zX6SD5Wut02Cv+YJKeS5IP9sZO3xOex08yja7OT6FMDl6dB2ZrnLrRmtfeDwvEzjQvyXmhcPOC9E/Z/jnNFTdEcOQN6ChrOAS/Z5sHmMi7On6+Qpgo9hNQBLzJVbS3YKwfISvrdtm6q5VZ2IcpkvoXx/fiwBmtjR0nOnk2CYD5qNW6vE07OBYkN0G3+4+u/OzY9KCW6dDyMfft5OPtuwT+54WWEQjGCTNFYt+mDgAo5cj1lpErWebFe/tBlbY5DHiKYTu2xKtASLQ60hsRA/affRIRUuA0UmIfrzVUT2TACamQ95KtYKC1ufupvXgX4IDOLAL8ZNKgBSiOoLxItWGo1AJo75QHxkKSflFsQvM6DeG+x22iHBaHQuSxhGDJKOwa/DF+6W4cYFNV6rUFwnV9afPAIPHdYnrTA0DoC6plphm5+ynN8qMoZbvORu2f6V2ncqFyFHKiA9STpclZK3NYIvsz7n1QJaOUAFrah1rwebpniMis+GN5/IoW8xUB+1nl9O5PAXisamxf3M8Sk=
  - secure: Hu0M1XOTCaG5317OQZN6jvwqObjd4laIK3pn/2iocn+JFmdeY+sD6If/iXreXGRPUuDar2a8+Fd2GE+99pr33gYQI86NMcNLXNm46zz1MhAUalb7o7eY4Tcd8Rk7DciTqW2fAcXoi9eh5Lbgc8/1LWwxRp13cBVSfi/rsOOYseQO7vKPpIpcKUqvfYiw3sa2ZKkc+wUGBh7JZdlTFV+iqmscIWtpvvRbEvsBwfP59r2wXpblJURe1Rh32c7EZJHtV8Iynf8OqoC2Go2a4MCI6CFOfLpbWq4CNAHFYnleUO56l644xgFjCrx+Sjo8pc7lNYMEjo4JgM6gyNocEuRF2X9AGX+g/A5mYdhZn2U8le+n9z9ywgyWB9PCuKQlr9o+o3ySANXEL2CHkVg3tXyEF+lo7fHiS7qaO7vHcKqreeoRJuUjmJa6Ggp7IHiizBy4WAhfhrCrsqP7LkcTDxBsSBFOmjo//iERCzaJqiXfHFNhChkWTew386bdIKpHjfi5XyihzjV6b2AWOA+UpesP1C8xdkXW2KP7LiRZi12c6MQbfIFLuRnoXanWLJKA5HY0vQpRvDfe8bpWxBpkESOOGjGF/8LXhYnRqNa/t1xxj0AxglA2B8rNnmLYkNpBHs42/J83w+1VwT8C4+OF4HfPtDkAN1Sb2PMJPABbEPa05wE=
  - secure: X0kuHQ2utEcitwhlYiDgmwiRN+PQzkjvWe4xXSNxcSVPiGK1jb7bkKq1m18cfm1fZFgdESEKtE1LXHyVktXqupFiXYgwusUHkNYPouMg35XL3yR8VQnv4nwM3PrToYHKl0u6C+RoljabPirb9D3riNShi6wRO+knxjvAx5Q9fP3xm81Y8kcucO430bdWDgfdYPW+GLi4b/HmHBXmYI3Nq2V4VxvFQAVVjHNXx2L5uRaEnnV4/z5zjfERzeHhzRWQzd9c5y4bD6QUQMNrqHLxFbWtTTPUd9niuSCc47VGC96qWcf6VvG65SugNtqfpFLxIp+A59PaKNxF6jK9+vobRNoXJVliZk9Z5Pfi3gf1s6rybgzxJ2oVxj+46s/EwTapojxaCNRXPfmE3pJrMW8RKRiHEfATTejir/PCEq5er/5r5CopcSiX94du3JNdRvqQgZd3uzmhdBBp3u8974MMoFjKDNtJfOagH+gmE9KJNzrwxQd6cxXdwxUuzPEZ9s2rgdi9yUqrEXIxy6vFI0ObGOhhy1vXli5FSyEjqvYrW7TJ7edH12/xgr7Rzket43Alr9/KNmXG8alZM0G68/WoRGtsO/qdTw0nXZ8iTCgS0GnmhF1xLuViWPMPWHOPdhkmWSFL2XCbSXCVhBtr/6agTz+aPz5bISUS5J51SBy7JWA=
  - PGENDPOINT=cp5x0h51kjd8m4.cg5ybcpnkj4u.us-east-1.rds.amazonaws.com
  - PGUSERNAME=example
  - PGPASSWORD=serverless
  - npm_config_PGCON=postgresql://example:serverless@cp5x0h51kjd8m4.cg5ybcpnkj4u.us-east-1.rds.amazonaws.com:5432/floods
  - npm_config_PGRUNCON=postgresql://floods_postgraphql:xyz@cp5x0h51kjd8m4.cg5ybcpnkj4u.us-east-1.rds.amazonaws.com:5432/floods
  - POSTGRAPHQL_ENDPOINT=https://5199xk4uxc.execute-api.us-east-1.amazonaws.com/dev/graphql
  - CURRENT_FLOODS_BRANCH_NAME=sync-legacy-statuses
  - FRONTEND_URL=localhost
  - GMAIL_ADDRESS=fake@gmail.address
