language: node_js
node_js:
- 8
addons:
  postgresql: 9.5
  apt:
    packages:
    - postgresql-9.5-postgis-2.3
services:
- postgresql
install: yarn;
before_script: yarn init-local-db; yarn local-drop-rebuild;
script: yarn start-express-server & yarn test;
deploy:
  provider: script
  script: yarn add global serverless@1.25.0; yarn; yarn rebuild-and-deploy-with-tons-of-crossings;
  on:
    all_branches: true
    condition: "$AWS_ACCESS_KEY_ID"
env:
  global:
  - secure: IroI4O/7RbjklOYzCPAoqk+wqB8t7jVQLdhqe1myRh38hrvkoMpiFgbZLx9sTDmMnr+qvLEgW/VIGm9/O0zvSxUn0+Tr1kdiHp4r4TljHEajB8zpj75gdPj/rKbptnJyQNSUhrsNqe+TYI9dZtU/VeqSlcYEBZl/bcF5F4oNdSvFKGZlOdrLRnX/2In9yNyCpB8JL5mSrGOUe3bEDzIec+FwluE7LjSeqqX8+a4JPtmIsa+2fMANwOVSxsVScpEtCMitbEHUrfulA3onjfyK6nB8qc3w6kfP8O6+C8DEqRXnkI6VHI1EFG5vFC/G2e3S0IssdNmDy5KoXqi9fp5hRXFTJcZj5IIm9f0+177ac8rmuyoMWcaOIYmznhgPFrzjK9iOPtGEDcFUer+Vvq44EWR5Mm9QXGaSy4cAat3tR4nreDRGf04cf9hC/jeEpVogbPI6WlN7xWqUzjXxdhtvk11OgiMQ/pbFFgvsda9skuniJn8SD5VRhH0WkUsZC8uzKoLUXWhEVqJsrOsQqjqUuSIAN++uibnLdrokc48Z17l7OX6yq3yB1mFlrXmYsjSKpuU3sO0q7X+1qpBhi09oX2QJuJuapQNUsfA+rX2aIYlgSUzWRpqRLWd8uKRb/24DGrXaElBWnvDXLnUWHyP6M4rJfL7xVUSEf4PmTwT/GnA=
  - secure: WiH7GLWYkJ8f9OjnljwKbjtha2hyA+1Li+Y4MH7wXi2NNcc4UV6YFxTYs1FYG4a8lyIcFH3K/YM858gelQfQObCO43ojiGCCMSOOLmawt6S/MTFXOSxUM0X6xKFjAGrTU1vpyMXfwssQivPULXXHF+RGo8ViPWWS9gbpFElQBRHEOGosh9E4P7PDj0rIVWIg6CMvb/VvX/35SZ+exC4KB5rEwgq5GNjNopD4zmDr/CLUs2bxRCt5FvNj1K4vmg2ngwI4UgD1yWKmiMMqKE9/8QSSqbKGzKj9GFsrnXEY6gjc2DYqNF+2L6dGK71GqPsj2wIjiy3+SfgQbdhNAQG0tGv3DKxbPN9zH7HwHYQYsARDMx8IJWOSXOY1tayQa7WfrWaTUKYCbgRBKCabjwQAHpHSsk/W2SahrH7jZbI41AS/+GJ9N4wKbbCS8kQ4CSoCfZ2FyZ0eQ8uvHEunEIQ6BSx8ViXWFAaJZvk9P0maE7nLZlnYXQIySnWm11kBc++2k87S8A0WMV+1bfyfrsdJC68+uxXDyROmr2RIETGAqG0rE+ZyW3r9Id7rmlmblJ05J/wpb9pNlbbRs543UEg5Ubo7KTrIzbli/0W8qtkY1/L4AkKVv55J4YmqNveU9dfxcyfhXQucIRP/XI0ZvJnaZjIHP1Fv+na9oId8YyhAFwE=
  - secure: VNATs9UGF3ggPVaWTZEjW286zZfjLi52JYQ48eMwMlfWHvKSvppYpAjwlQZfJBAnhPxGynCgwJsGmtbvRvkL3cbK9Zc0YFFgNqId1EKI+MVyo+XQEsoPxi/a8geqNt81RQDOEE3j4E2HkX0YINSrkvIA4JKWbzPpnU5bKtmktFH8mrZzq8w2PzJhWZn5YO11+k1aWjC+BoqJPBFJmYYpRsFEaICAkhiG1JscecooIGlFfBsxD402jFTwJgLb53pAHbmMsl+3DyDSphqztIwSRFVuhFrLqUQqlSbAHzDqQdvJIieO1GKHngYn9kXA6QQYiq44EnE2UaRzG9ZrlEWBiKVnU+tVRY7RWFig3UslGuqwGmNWuXNkKKOpmtHezKqMiGK1kx7d/0OS8qwuTrLOOEQJOsoazyTe8t6V19LAMVaj/uCP/ghtZjJmmsxvmlXBBYStfTfL0xJo1D1+saouV6TMk3Ldmb/jyGXBE12RcEeDpZcFPQp1oRCrIhy+3FCS9TLlvT7t/mWhhlOuSUblGK8ribyuoEm3f/6xzjsgw8DvQ78Le+RGAbafRdDriP/t7c0Djv1nqzpfpUcumwGHGbd4JYO7enIxUqGmEU3mM1Z4uTxOBt0E+eDaF2uK9AFAV03ZyIn1dxPVD/dCGFPxYTD6ZovyG73Zq6nhOpofbtI=
  - secure: b+JomLGxiL3LHE5QhXjo+L5NWaiT8M9Jrb+w9p3i4Lq6SGdOY2kYlxL4oVGKfbJkjt+88DQfrlKyCmTtSVocu78M362lyKDgRokxoE1OCtEx4Y/6zgpxqsYnM6t2He4KdcmZvyp9hJmhUIwGGWNs95NGe0xfqy1afq4C02FXzfnk+sbeUgChgzoVmZ8uwcaE7wzveqhzPjmMDG/JDEfBIIH8VEium32tbx4C+8oSwHdTWseDzqBv7FsQlX5GXfgDD6i1/asBIlsNia3z/42vfc7w3F2V0S1WLVTFNo3LEXAuHTV1Ro0s7N+c33srZWctOhQQHrqJsAYcNOooOaUorbzlo1L5iwm5mr8Ee90oNlfXmiKaVfL9hIjAkttKA0A3lYc6Ofuvt+tBki5kFPtIqlxvI1pPMeickuIQ0ppS4ahjkpJwH2zmp+tnL+BKrE6RF3fxo5LR8iP/Fjx7K5WpWPXCdJIFmGNaXTV0mhHAH1ATyeK7P1nEGGweBk7AR0BYI5NTnRitNX1FWS1vPkPQwozEMOh6yInP2TgtzZcXXl5FTv95Sug7yGlFEuaUZ+mcuVhVDnOsTLSbMHlD6regATjtjoWfYIHQ89RoO+8DYc6kgOnx24XG1SqPWPNpP0oMLrNLdWbEc0Frsl4Qe3ra8zEMiOgneB4AeetMPtMHEVU=
  - npm_config_PGCON=postgresql://example:serverless@cp1f2kf17sdpifd.cg5ybcpnkj4u.us-east-1.rds.amazonaws.com:5432/floods
  - npm_config_PGRUNCON=postgresql://floods_postgraphql:xyz@cp1f2kf17sdpifd.cg5ybcpnkj4u.us-east-1.rds.amazonaws.com:5432/floods
  - POSTGRAPHQL_ENDPOINT=https://6ci5jtwj5m.execute-api.us-east-1.amazonaws.com/dev/graphql
  - CURRENT_FLOODS_BRANCH_NAME=gzip-responses
  - FRONTEND_URL=localhost
  - GMAIL_ADDRESS=fake@gmail.address
